#!/bin/bash
###
# I copied a few things from somewhere on the web (mainly from the arch forums)
###

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

if [ -f /usr/local/git/contrib/completion ]; then
  . /usr/local/git/contrib/completion/git-completion.bash
fi

# sudo completion
complete -cf sudo

# set PATH so it includes user's private bin if it exists
if [ -d ~/.bin ] ; then
PATH=~/.bin:"${PATH}"
fi

if [ -d ~/.local/bin ]; then
PATH=~/.local/bin:"${PATH}"
fi

# Global environment definitions
# ------------------------------
export WORKON_HOME=~/.virtualenvs    # See: https://wiki.archlinux.org/index.php/Python_VirtualEnv#Virtualenvwrapper
source /usr/bin/virtualenvwrapper.sh
VIRTUAL_ENV_DISABLE_PROMPT=1 # don't let virtualenv show prompts by itself
export PYMACS_PYTHON=python2
export HISTCONTROL=ignoredups # don't put duplicate lines in the history
export HISTCONTROL=ignoreboth # ignore same sucessive entries.
export HISTCONTROL=erasedups  # ignore duplicate entries in history
export HISTSIZE=10000         # Increases size of history
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear:clr:[bf]g"
shopt -s histappend   # Append history instead of overwriting
shopt -s cdspell      # Correct minor spelling errors in cd command
shopt -s dotglob      # includes dotfiles in pathname expansion
shopt -s checkwinsize # If window size changes, redraw contents
shopt -s cmdhist      # Multiline commands are a single command in history.
shopt -s extglob      # Allows basic regexps in bash.
shopt -s checkwinsize # update the values of lines and columns.
set ignoreeof on      # Typing EOF (CTRL+D) will not exit interactive sessions

export EDITOR='vim'


# Aliases
# ---------------------------------------------------------
# get an ordered list of subdirectory sizes
alias dux='du -skh ./* | sort -h | grep -v total && du -cskh ./* | grep --color=never total'

alias install='sudo pacman -S'
alias remove='sudo pacman -Rns'
alias search='pacman -Ss'
alias update='packer -Syu'
alias remove_unused='sudo pacman -Rns $(pacman -Qqtd)' # See: http://bbs.archbang.org/viewtopic.php?pid=13120#p13120
alias searchlocal='pacman -Qs'
alias showinfo="pacman -Si"    # '[i]nfo'    - show information about a package
alias listorphans="pacman -Qdt"    # '[l]ist [o]rphans'  - list all packages which are orphaned
alias clearcache="sudo pacman -Scc"    # '[c]lean cache' - delete all not currently installed package files
alias listfiles="pacman -Ql"   # '[l]ist [f]iles'  - list all files installed by a given package
alias aurupdate='packer -Syu --auronly --noedit --noconfirm'
alias aurinstall='packer -S'
alias aursearch='packer -Ss'
alias aurdevel='packer -Syu --devel'

alias ..='cd ..'
alias ...='cd ../..'
alias ls='ls --color=auto'
alias l='ls -vphl --color=auto --group-directories-first --time-style="+%d-%m-%Y %H:%M"'
alias ll='ls -vphlA --color=auto --group-directories-first --time-style="+%d-%m-%Y %H:%M"'

alias grep='grep --color=auto'
alias ping='ping -c 5'
alias df='df -h'
alias clr='clear;echo "Currently logged in on $(tty), as $(whoami) in directory $(pwd)."'
alias tarc='tar -pczf'
alias tare='extract'

alias bitch,='sudo' # for the lulz

alias nano='vim'
alias ec='emacsclient -c -n -a vim'
alias et='emacsclient -t -a vim'

# private aliases.. e.q. ssh aliases
if [ -f ~/.bash_alias_private ]; then
    . ~/.bash_alias_private
fi



# These functions make my life easier :)
function extract () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2) tar xvjf $1;;
            *.tar.gz) tar xvzf $1;;
            *.bz2) bunzip2 $1;;
            *.rar) unrar x $1;;
            *.gz) gunzip $1;;
            *.tar) tar xvf $1;;
            *.tbz2) tar xvjf $1;;
            *.tgz) tar xvzf $1;;
            *.zip) unzip $1;;
            *.Z) uncompress $1;;
            *.7z) 7za x $1;;
            *) echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
	echo "'$1' is not a valid file"
    fi
}

function exip () {
    echo -n "Current External IP: "
    curl -s -m 5 http://myip.dk | grep "ha4" | sed -e 's/<b>IP Address:<\/b> <span class="ha4">//g' -e 's/<\/span><br \/><br \/>//g'
}


function psgrep() {
  ps aux | grep "$1" | grep -v "grep"
}

function mkcd() {
  mkdir -p "$1"
  cd "$1"
}

# This will update your requirements.txt file to the latest applications
function update_pip_deps {
  echo "Generating dependencies without version number..."
  pip freeze | cut -d = -f 1 > $1
  cp $1 requirement2.txt
  echo "Trying to get the latest packages available at PyPI..."
  pip install --upgrade -r $*
  echo "Generating new requirements.txt file for the latest packages..."
  pip freeze > $1
}

function clean_pip_deps {
  echo "Generating dependencies from requirements.txt file without version number..."
  cat requirements.txt | cut -d = -f 1 > requirements2.txt
  echo "Done."
}

# Useful command for stripping whitespace
function remove_trailing_whitespace() {
  find . -name $* -exec sed -i '' -e's/[[:space:]]*$//' {} \;
}

# Userful for replacing tabs with spaces
# $1 --> file ending. for example: `convert_tabs_to_spaces .py`
# this will convert all taps to spaces from all *.py files recursively
# in the directory
function convert_tabs_to_spaces() {
    find . ! -type d ! -name _tmp_ -iname "*$1" -type f -exec sh -c 'expand -t 4 {} > _tmp_ && mv _tmp_ {}' \;
}

# My Bash-Prompt
# Reset
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Underline
UBlack='\e[4;30m'       # Black
URed='\e[4;31m'         # Red
UGreen='\e[4;32m'       # Green
UYellow='\e[4;33m'      # Yellow
UBlue='\e[4;34m'        # Blue
UPurple='\e[4;35m'      # Purple
UCyan='\e[4;36m'        # Cyan
UWhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
IBlack='\e[0;90m'       # Black
IRed='\e[0;91m'         # Red
IGreen='\e[0;92m'       # Green
IYellow='\e[0;93m'      # Yellow
IBlue='\e[0;94m'        # Blue
IPurple='\e[0;95m'      # Purple
ICyan='\e[0;96m'        # Cyan
IWhite='\e[0;97m'       # White

# Bold High Intensity
BIBlack='\e[1;90m'      # Black
BIRed='\e[1;91m'        # Red
BIGreen='\e[1;92m'      # Green
BIYellow='\e[1;93m'     # Yellow
BIBlue='\e[1;94m'       # Blue
BIPurple='\e[1;95m'     # Purple
BICyan='\e[1;96m'       # Cyan
BIWhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White

# Git Prompt
source /usr/share/git/completion/git-prompt.sh
# * for unstaged and + for staged changes
#GIT_PS1_SHOWDIRTYSTATE=true
# $ if something is stashed
#GIT_PS1_SHOWSTASHSTATE=true
# % if there are untracked files
#GIT_PS1_SHOWUNTRACKEDFILES=true


# A few prompts (most of them are from the archwiki)
#PS1="\[$BGreen\]\u\[$BCyan\]@\[$BGreen\]\h \[$BBlue\]\w\[$BBlue\]\$(__git_ps1 ' (%s)') $ \[$Color_Off\]"

PS1="\[$White\]┌─[\[$Blue\]\u\[$White\]][\[$Green\]\h\[$White\]][\[$Purple\]\w\[$White\]]\[$Cyan\]\$(__git_ps1 '[%s]')\n\[$White\]└──╼ \[$Color_Off"
PS2="╾──╼ "

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#From_Arch_Forum_.231
# https://bbs.archlinux.org/viewtopic.php?pid=1068202#p1068202
#PS1="\[\033[0;37m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[0;31m\]\h'; else echo '\[\033[0;33m\]\u\[\033[0;37m\]@\[\033[0;96m\]\h'; fi)\[\033[0;37m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;37m\]]\n\[\033[0;37m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]"

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#From_an_italian_blog.E2.80.A6
#if [[ ${EUID} == 0 ]] ; then
#  sq_color="\[\033[0;31m\]"
#else
#  sq_color="\[\033[0;34m\]"
#fi
#PS1="$sq_color\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[01;37m\]\342\234\227$sq_color]\342\224\200\")[\[\033[01;37m\]\t$sq_color]\342\224\200[\[\033[01;37m\]\u@\h$sq_color]\n\342\224\224\342\224\200\342\224\200> \[\033[01;37m\]\W$sq_color $ \[\033[01;37m\]>>\\[\\033[0m\\] "
#unset sq_color

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#A_well-established_Bash_color_prompt
#PS1="\[$BGreen\]\u@\h\[$BBlue\] \w\$([[ \$? != 0 ]] && echo \"\[$BRed\]:(\[$BBlue\]\")\\$\[$Color_Off\] "
