#!/bin/bash

# Bash Colors
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Underline
UBlack='\e[4;30m'       # Black
URed='\e[4;31m'         # Red
UGreen='\e[4;32m'       # Green
UYellow='\e[4;33m'      # Yellow
UBlue='\e[4;34m'        # Blue
UPurple='\e[4;35m'      # Purple
UCyan='\e[4;36m'        # Cyan
UWhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
IBlack='\e[0;90m'       # Black
IRed='\e[0;91m'         # Red
IGreen='\e[0;92m'       # Green
IYellow='\e[0;93m'      # Yellow
IBlue='\e[0;94m'        # Blue
IPurple='\e[0;95m'      # Purple
ICyan='\e[0;96m'        # Cyan
IWhite='\e[0;97m'       # White

# Bold High Intensity
BIBlack='\e[1;90m'      # Black
BIRed='\e[1;91m'        # Red
BIGreen='\e[1;92m'      # Green
BIYellow='\e[1;93m'     # Yellow
BIBlue='\e[1;94m'       # Blue
BIPurple='\e[1;95m'     # Purple
BICyan='\e[1;96m'       # Cyan
BIWhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White


# Git Prompt
# check if the file exists, otherwise download it
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    source /usr/share/git/completion/git-prompt.sh
elif [ -f ~/.git.d/git-prompt.sh ]; then
    source ~/.git.d/git-prompt.sh
else
    if [ ! -d ~/.git.d/ ]; then
        mkdir -p ~/.git.d/
    fi
    sudo curl -o ~/.git.d/git-prompt.sh https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh
    source ~/.git.d/git-prompt.sh
fi
# * for unstaged and + for staged changes
#GIT_PS1_SHOWDIRTYSTATE=true
# $ if something is stashed
#GIT_PS1_SHOWSTASHSTATE=true
# % if there are untracked files
#GIT_PS1_SHOWUNTRACKEDFILES=true

# A few prompts (most of them are from the archwiki)
#PS1="\[$BGreen\]\u\[$BCyan\]@\[$BGreen\]\h \[$BBlue\]\w\[$BBlue\]\$(__git_ps1 ' (%s)') $ \[$Color_Off\]"

PS1="\[$White\]┌─[\[$Blue\]\u\[$White\]][\[$Green\]\h\[$White\]][\[$Purple\]\w\[$White\]]\[$Cyan\]\$(__git_ps1 '[%s]')\n\[$White\]└──╼ \[$Color_Off"
PS2="╾──╼ "

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#From_Arch_Forum_.231
# https://bbs.archlinux.org/viewtopic.php?pid=1068202#p1068202
#PS1="\[\033[0;37m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[0;31m\]\h'; else echo '\[\033[0;33m\]\u\[\033[0;37m\]@\[\033[0;96m\]\h'; fi)\[\033[0;37m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;37m\]]\n\[\033[0;37m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]"

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#From_an_italian_blog.E2.80.A6
#if [[ ${EUID} == 0 ]] ; then
#  sq_color="\[\033[0;31m\]"
#else
#  sq_color="\[\033[0;34m\]"
#fi
#PS1="$sq_color\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[01;37m\]\342\234\227$sq_color]\342\224\200\")[\[\033[01;37m\]\t$sq_color]\342\224\200[\[\033[01;37m\]\u@\h$sq_color]\n\342\224\224\342\224\200\342\224\200> \[\033[01;37m\]\W$sq_color $ \[\033[01;37m\]>>\\[\\033[0m\\] "
#unset sq_color

# https://wiki.archlinux.org/index.php/Color_Bash_Prompt#A_well-established_Bash_color_prompt
#PS1="\[$BGreen\]\u@\h\[$BBlue\] \w\$([[ \$? != 0 ]] && echo \"\[$BRed\]:(\[$BBlue\]\")\\$\[$Color_Off\] "
