#!/bin/bash

# Platform detection
# ------------------------------
platform='unknown'
distribution='unkown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
   distribution=$(awk '/^NAME=/ { print $0 }' /etc/os-release | cut -d '=' -f 2 | tr -d '\"')
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='darwin'
   distribution=$(sw_vers -productVersion)
fi


# Completions
# ------------------------------
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

if [ -f /usr/local/git/contrib/completion ]; then
  . /usr/local/git/contrib/completion/git-completion.bash
fi

# sudo completion
complete -cf sudo
# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# osx specific
if [ $platform == "darwin" ]; then
    complete -W "NSGlobalDomain" defaults
    complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall # Add `killall` tab completion for common apps
fi

# LESS source highlighting
if [ -f /usr/local/bin/src-hilite-lesspipe.sh ]; then
    # osx
    export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
    export LESS=" -R "
    # add -N for line numbers
    alias less='less -m -g -i -J --underline-special --SILENT'
elif [ -f /usr/bin/src-hilite-lesspipe.sh ]; then
    # arch/debian
    export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
    export LESS=" -R "
    alias less='less -m -g -i -J --underline-special --SILENT'
fi

# Additional $PATH paths
# ------------------------------
# set PATH so it includes user's private bin if it exists
if [ -d ~/.bin ] ; then
    PATH=$HOME/.bin:"${PATH}"
fi

if [ -d ~/.local/bin ]; then
    PATH=$HOME/.local/bin:"${PATH}"
fi

if [ -d $HOME/.rvm/bin ]; then
    PATH=$HOME/.rvm/bin:"${PATH}"
fi

# Global Environment Definitions
# ------------------------------
export EDITOR='vim'
export WORKON_HOME=~/.virtualenvs
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then # OSX and Debian
    source /usr/local/bin/virtualenvwrapper.sh
elif [ -f /usr/bin/virtualenvwrapper.sh ]; then     # Arch Linux
    source /usr/bin/virtualenvwrapper.sh
fi

VIRTUAL_ENV_DISABLE_PROMPT=1  # don't let virtualenv show prompts by itself
export PYMACS_PYTHON=python2
export HISTCONTROL=ignoredups # don't put duplicate lines in the history
export HISTCONTROL=ignoreboth # ignore same sucessive entries.
export HISTCONTROL=erasedups  # ignore duplicate entries in history
export HISTSIZE=10000         # Increases size of history
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear:clr:[bf]g"
shopt -s histappend   # Append history instead of overwriting
shopt -s cdspell      # Correct minor spelling errors in cd command
shopt -s dotglob      # includes dotfiles in pathname expansion
shopt -s checkwinsize # If window size changes, redraw contents
shopt -s cmdhist      # Multiline commands are a single command in history.
shopt -s extglob      # Allows basic regexps in bash.
shopt -s checkwinsize # update the values of lines and columns.
set ignoreeof on      # Typing EOF (CTRL+D) will not exit interactive sessions

if [ $platform == "darwin" ]; then
    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
fi

# Public Aliases
# ------------------------------
. ~/.bash.d/bash_aliases


# Private Aliases
# ------------------------------
if [ -f ~/.bash.d/bash_alias_private ]; then
    . ~/.bash.d/bash_alias_private
fi


# Functions / Helpers
# ------------------------------
. ~/.bash.d/bash_functions


# Prompt
# ------------------------------
. ~/.bash.d/bash_prompt

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
